# kubectl anykap init mykap
# runs on a self-hosted agent
name: anykap
on: [push, workflow_dispatch]
jobs:
  check-bats-version:
    # choose runner on label
    runs-on: [self-hosted, linux, x64, anykap]
    steps:
    - uses: actions/checkout@v4
    # Check the cluster config
    - name: Check home folder
      run: |
        realpath ~
    - name: Check cluster config
      run: |
        kubectl config current-context
    - name: apply kustomization
      run: |
        kubectl apply -k ~/anykap/anykap-example/.
    - name: Check kap pod
      working-directory: ~
      run: |
        kubectl get po -l app.kubernetes.io/instance=mykap
    - name: Check kap artifact
      run: |
        . ~/anykap/.anykap-venv/bin/activate
        cd ~/anykap/anykap-example
        kubectl anykap a